[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
castagne_backend = "GNmXt5Lp6RXYyZKCpTBvcv5oPiEh2TzgSPiL9h43uBa3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
